### ISSUE TITLE
skbio.io._exception.IOSourceError when i build the tree

### ISSUE THREAD

**Issue by NElight** [JTFouquier/ghost-tree#80]
when i use the command line 
```
ghost-tree silva extract-fungi $silva_aligned $silva_accession $silva_taxonomy $silva_fungi_only
```
i got an error with skbio.io like this 
```
Traceback (most recent call last):
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/bin/ghost-tree", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/PUBLIC/software/MICRO/python/ghost-tree/scripts/ghost-tree", line 267, in <module>
    cli()
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/PUBLIC/software/MICRO/python/ghost-tree/scripts/ghost-tree", line 135, in extract_fungi
    taxonomy_file), into=output_file, format="fasta")
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/skbio/io/registry.py", line 1166, in write
    return io_registry.write(obj, format, into, **kwargs)
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/skbio/io/registry.py", line 619, in write
    writer(obj, into, **kwargs)
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/skbio/io/registry.py", line 1080, in wrapped_writer
    with open_files(files, mode='w', **io_kwargs) as fhs:
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/skbio/io/util.py", line 276, in open_files
    yield [stack.enter_context(open_file(f, **kwargs)) for f in files]
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/skbio/io/util.py", line 276, in <listcomp>
    yield [stack.enter_context(open_file(f, **kwargs)) for f in files]
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/contextlib.py", line 330, in enter_context
    result = _cm_type.__enter__(cm)
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/skbio/io/util.py", line 246, in open_file
    with _resolve_file(file, **kwargs) as (file, source, is_binary_file):
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/skbio/io/util.py", line 203, in _resolve_file
    file, source, is_binary_file = _resolve(file, **kwargs)
  File "/PUBLIC/software/MICRO/miniconda/miniconda3/lib/python3.6/site-packages/skbio/io/util.py", line 65, in _resolve
    "Could not open source: %r (mode: %r)" % (file, mode))
skbio.io._exception.IOSourceError: Could not open source: <_io.TextIOWrapper name='silva_fungi_only.txt' mode='w' encoding='ISO-8859-15'> (mode: 'w')
```
,how i can solve that

**Comment by JTFouquier** [comment]
Hi @NElight, thank you so much for reporting this! 

It looks like these issues are related to skbio updates, and they were not caught in the unit tests for some reason when I pushed the last code. I'll push a fix soon. -Jennifer

**Comment by NElight** [comment]
HI @JTFouquier ,

**Comment by NElight** [comment]
hi @JTFouquier ,
thank you.

**Comment by JTFouquier** [comment]
Hello @NElight, sorry for the delay. I just pushed a fix. This was related to updates in skbio that weren't handled by my unit tests. Not a big deal, just normal stuff as code is improved. Please update your code base, and reinstall ghost-tree.  If you have any questions please email me at jennietf@gmail.com or open a new issue. Thanks for letting me know!

**Comment by NElight** [comment]
hi，@JTFouquier 
thank you.

**Comment by NElight** [comment]
hello, @JTFouquier . i also have the same error. i do not know what is wrong.

**Comment by JTFouquier** [comment]
Ok, I'll check again. So you're still having trouble with the same command? I was able to get the command you posted to work and I received `silva_fungi_only` as output. Did you do `pip install -e .` to reinstall the code? Thanks!

**Comment by NElight** [comment]
hi， @JTFouquier . i am very sorry to bother you . it was because of my mistakes。 thank you again.
